export {default as Hero}from './hero/Hero'
export {default as Features}from './features/Features'
export {default as Showcase}from './showcase/showcase'
export {default as Pricing}from './pricing/Pricing'
export {default as Blog} from './blog/Blog'
export {default as Cta} from './cta/Cta'
export {default as Faq} from './faq/Faq'
